apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-pki-mynet
  namespace: cert-manager
spec:
  vault:
    path: pki_int/sign/mynet-wildcard
    server: "http://vault.mynet"
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager
        serviceAccountRef:
          name: cert-manager
